### ISSUE TITLE
Capitalize constants

### ISSUE THREAD

**Issue by ethers** [brave-intl/basic-attention-token-crowdsale#1]
```
    uint256 public constant batFund = 500 * (10**6) * 10**decimals;   // 500m BAT reserved for Brave Intl use
    uint256 public constant tokenExchangeRate = 5500; // 5500 BAT tokens per 1 ETH: THIS MAY CHANGE AT DEPLOY TIME
    uint256 public constant tokenCreationCap =  1500 * (10**6) * 10**decimals; 
    uint256 public constant tokenCreationMin =  750 * (10**6) * 10**decimals; 
```

Consider capitalizing constants to improve readability when they are used.

http://solidity.readthedocs.io/en/develop/style-guide.html#constants

> Constants should be named with all capital letters with underscores separating words. (for example:MAX_BLOCKS)

(This would also be more in line with conventions in other languages.)

**Comment by maraoz** [comment]
+1!
