### ISSUE TITLE
remove unneeded else branch 

### ISSUE THREAD

**Issue by maraoz** [brave-intl/basic-attention-token-crowdsale#10]
else branch in [line 58 of BATToken.sol](https://github.com/brave-intl/basic-attention-token-crowdsale/blob/master/contracts/BAToken.sol#L58) is not needed, as if-branch throws and ends execution. Consider moving the else branch outside of the if-else.

**Comment by nfnty** [comment]
Already opened a PR for this, which was closed: #9.

**Comment by locklin** [comment]
Merged pull request; sorry for misunderstanding. FWIIW, saved 1 gas, and I suppose it's easier on the eyes.
