### ISSUE TITLE
`tokenCreationMin` reached but haven't reached the exact `tokenCreationCap`

### ISSUE THREAD

**Issue by elenadimitrova** [brave-intl/basic-attention-token-crowdsale#11]
A concern for the logic here

https://github.com/brave-intl/basic-attention-token-crowdsale/blob/master/contracts/BAToken.sol#L70

In a scenario where potentially you get close to the `tokenCreationCap` and no transaction with the exact remaining value is submitted, the sale will fail and you won't be able to finalize.

**Comment by nfnty** [comment]
Not true. `ethFundDeposit` would just need to wait for `fundingEndBlock` to execute `finalize()` in that case.

**Comment by locklin** [comment]
Integer division by an exchange rate with unpleasant prime numbers is annoying and makes this "wait until the end for finality" possible. trying to keep the exchange rate a clean factor. Meanwhile waiting until the end of the month for the eth and finality is annoying but OK.
