### ISSUE TITLE
msg.value is in wei, tokenExchangeRate expects ether

### ISSUE THREAD

**Issue by cryptogoth** [brave-intl/basic-attention-token-crowdsale#13]
This line of the token creation function creates tokens at the specified exchange rate when users pay into the contract.
https://github.com/brave-intl/basic-attention-token-crowdsale/blob/master/contracts/BAToken.sol#L55

The comment where the exchange rate is declared implies that 1 ether should get 8000 BATs.

I've deployed this contract to Rinkeby here:
https://rinkeby.etherscan.io/address/0x6f036e95c0503f3456059b8a6ec5c81a6d7bfdfa

and tested it with these geth commands.
```
> batokenInstance.ethFundDeposit()
"0x83fa180e1557b6598b15d2de154bbef657f8fafe"
> batokenInstance.batFundDeposit()
"0x83fa180e1557b6598b15d2de154bbef657f8fafe"
> batokenInstance.createTokens({from: eth.coinbase, value: 1})
"0xcd053194880ff6f6ab1ab8af85eaffbe858fe948a7cca88f1f86c1fdaa0180c7"
> batokenInstance.balanceOf(eth.coinbase)
8000
```

After paying in 1 wei, I get 8000 BATs, which is not the intended amount.
For 1 wei, I should get 8000 / 10e18 BATs, which would be rounded down to 0 since the variable `balances` is a map of address to type `unit256`.

**Comment by JeromeLoo** [comment]
so it's a bug?

**Comment by JeromeLoo** [comment]
value:1 means 1wei or 1eth

**Comment by nfnty** [comment]
It's working exactly as intended; you have to account for the decimals. 1 BAT is actually a balance of `10**18`. What you're getting when paying one wei is `8000*1*10**-18` BAT.

**Comment by locklin** [comment]
?? I am perplexed by this.
When you use ethereum frameworks like web3 or solidity or whatever, everything is in wei. You're getting 8000 "BAT wei" back. You only get whole numbers like ETH in wallet software. If you look at the source code there are all kinds of 10**18 numbers to account for the fact that wei are the natural increments in ethereum.
As nfnty said: this is how it's supposed to work.

**Comment by cryptogoth** [comment]
Thanks for clarifying my misunderstanding. Having the token subdividable to the same decimal (10**18) as ether<->wei makes it easy to calculate.
