### ISSUE TITLE
BAT testnet token sale should use Rinkeby

### ISSUE THREAD

**Issue by cryptogoth** [brave-intl/basic-attention-token-crowdsale#14]
The BAT testnet token sale uses the Ropsten testnet, which is extremely slow right now due to DoS attacks and mining spam. Transactions routinely take days to clear, and it is therefore difficult to both receive Ropsten faucet ether, and also to spend it.

A better testnet to use and advertise on the website would be Rinkeby, for both funders and the contract devs to test out the contract in advance of the real sale on Wednesday.

I've deployed BAToken.sol here on Rinkeby, to end at block 280741 (about one day from the create date of this issue). Anyone is free to use for testing:

https://rinkeby.etherscan.io/address/0x6f036e95c0503f3456059b8a6ec5c81a6d7bfdfa

**Comment by locklin** [comment]
Thanks for this, but noobs will have a harder time with Rinkeby than with ropsten, which as far as I can tell is behaving itself just fine and hasn't been under attack in weeks.
The lack of simple taps is annoying, but we're sending ropsten eth to whoever asks in the slack.

**Comment by panzicong** [comment]
Thank you!
Spark by Readdle

**Comment by cryptogoth** [comment]
Thanks @locklin , I'll ask in the slack.
