### ISSUE TITLE
??? - is it a hack?

### ISSUE THREAD

**Issue by johndpope** [brave-intl/basic-attention-token-crowdsale#16]
<img width="987" alt="screen shot 2017-08-06 at 6 29 57 pm" src="https://user-images.githubusercontent.com/289994/29007629-5032efcc-7ad5-11e7-8522-ee0bcf51a6af.png">

**Comment by yordis** [comment]
@johndpope it is not, the reason you are see this is because it is not over `HTTPS` notice the `S` which means secure.

Normally you shouldn't be using any website over `HTTP` if you are transmitting sensitive information. They could fix this by enabling `HTTPS` and this will go away.
