### ISSUE TITLE
Number of crowdsale tokens

### ISSUE THREAD

**Issue by ethers** [brave-intl/basic-attention-token-crowdsale#2]
https://medium.com/@AttentionToken/bat-funding-increase-and-smart-contracts-928d1dbee27e states:

`The number of crowdsale tokens is increasing to 1 billion from 700 million, an increase of nearly 43%.`

how does that align with the code?

`    uint256 public constant tokenCreationMin =  750` million

https://github.com/brave-intl/basic-attention-token-crowdsale/blob/db73fc84975f868d78b1805b2d6a788ad520d4c5/contracts/BAToken.sol#L24

**Comment by locklin** [comment]
Please see :
https://github.com/brave-intl/basic-attention-token-crowdsale/blob/db73fc84975f868d78b1805b2d6a788ad520d4c5/contracts/BAToken.sol#L23

500m tokens are created at deploy time. 1b are sold making the upper bound 1.5b.
