### ISSUE TITLE
should support send ether to BAT contract address to participate ICO

### ISSUE THREAD

**Issue by yuanaichi** [brave-intl/basic-attention-token-crowdsale#5]
like this:
`
function () payable {
    //call create tokens
}
`

**Comment by locklin** [comment]
I had a feeling someone was going to ask for this. 

I do not want this, as I figure someone who can't add 0xb4427263 to their transfer or use an ABI file is also likely to send ETH from coinbase or something which they will also complain about. The instructions (to be published today-ish) all refer to sending function signatures.
